"use client";
import "./finance-app.css";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowDownLeft, ArrowUpRight, BarChart3, Check, CreditCard, LayoutDashboard, LogOut, Menu, Pencil, Plus, Search, Settings, Target, Trash2, WalletCards, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { cardAvailable, cardInvoiceTotal, categories, currentMonth, formatCurrency, formatDate, fromCents, goalProgress, monthName, monthTotals, toCents } from "@/lib/finance";
import type { CreditCard as Card, Goal, Transaction, TransactionType } from "@/types/finance";

type Page = "dashboard"|"movimentacoes"|"cartoes"|"metas"|"relatorios"|"configuracoes";
type Modal = "transaction"|"card"|"goal"|"adjust"|null;
const nav = [{page:"dashboard",href:"/dashboard",label:"Visão geral",icon:LayoutDashboard},{page:"movimentacoes",href:"/movimentacoes",label:"Movimentações",icon:ArrowDownLeft},{page:"cartoes",href:"/cartoes",label:"Cartões",icon:CreditCard},{page:"metas",href:"/metas",label:"Metas",icon:Target},{page:"relatorios",href:"/relatorios",label:"Relatórios",icon:BarChart3},{page:"configuracoes",href:"/configuracoes",label:"Configurações",icon:Settings}] as const;
const row = (x: unknown) => x as Record<string, unknown>;
const str = (x: unknown) => typeof x === "string" ? x : null;
const num = (x: unknown) => fromCents(toCents(x));
const transaction = (x:unknown):Transaction => {const r=row(x);return {id:String(r.id),description:String(r.description),amount:num(r.amount),type:r.type==="income"?"income":"expense",category:String(r.category),date:String(r.date),credit_card_id:str(r.credit_card_id),note:str(r.note)}};
const card = (x:unknown):Card => {const r=row(x);return {id:String(r.id),name:String(r.name),brand:str(r.brand),last_four:str(r.last_four),credit_limit:num(r.credit_limit ?? r.limit),closing_day:Number(r.closing_day??1),due_day:Number(r.due_day??10),color:str(r.color)}};
const goal = (x:unknown):Goal => {const r=row(x);return {id:String(r.id),name:String(r.name),target:num(r.target),current:num(r.current),due_date:str(r.due_date),description:str(r.description)}};
const today=()=>new Date().toISOString().slice(0,10);

export default function FinanceApp({page}:{page:Page}) {
 const router=useRouter(); const [transactions,setTransactions]=useState<Transaction[]>([]),[cards,setCards]=useState<Card[]>([]),[goals,setGoals]=useState<Goal[]>([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[modal,setModal]=useState<Modal>(null),[editTx,setEditTx]=useState<Transaction|null>(null),[editCard,setEditCard]=useState<Card|null>(null),[editGoal,setEditGoal]=useState<Goal|null>(null),[adjustGoal,setAdjustGoal]=useState<Goal|null>(null),[confirm,setConfirm]=useState<{text:string;run:()=>Promise<void>}|null>(null),[saving,setSaving]=useState(false),[menu,setMenu]=useState(false),[month,setMonth]=useState(currentMonth()),[search,setSearch]=useState(""),[type,setType]=useState<"all"|TransactionType>("all"),[category,setCategory]=useState("all");
 const alert=(message:string)=>setNotice(message); useEffect(()=>{if(!notice)return;const t=window.setTimeout(()=>setNotice(null),4500);return()=>clearTimeout(t)},[notice]);
 async function load(){setLoading(true);setError(null);try{const s=createClient(),u=await s.auth.getUser();if(u.error||!u.data.user)throw Error("Sua sessão expirou. Entre novamente.");setEmail(u.data.user.email??"");setName(String(u.data.user.user_metadata.full_name??""));const [t,c,g]=await Promise.all([s.from("transactions").select("id,description,amount,type,category,date,credit_card_id,note").order("date",{ascending:false}),s.from("credit_cards").select("id,name,brand,last_four,credit_limit,closing_day,due_day,color").order("created_at",{ascending:false}),s.from("goals").select("id,name,target,current,due_date,description").order("created_at",{ascending:false})]);if(t.error||c.error||g.error)throw Error("Não foi possível carregar os dados financeiros. Execute a migração do Supabase e tente novamente.");setTransactions((t.data??[]).map(transaction));setCards((c.data??[]).map(card));setGoals((g.data??[]).map(goal));}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar seus dados.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const months=useMemo(()=>[...new Set([currentMonth(),...transactions.map(x=>x.date.slice(0,7))])].sort().reverse(),[transactions]);
 const monthly=useMemo(()=>transactions.filter(x=>x.date.startsWith(month)),[transactions,month]); const totals=useMemo(()=>monthTotals(monthly),[monthly]); const balance=totals.income-totals.expense;
 const visible=useMemo(()=>monthly.filter(x=>(type==="all"||x.type===type)&&(category==="all"||x.category===category)&&(`${x.description} ${x.category}`).toLowerCase().includes(search.toLowerCase())),[monthly,type,category,search]);
 const cats=useMemo(()=>{const m=new Map<string,number>();monthly.filter(x=>x.type==="expense").forEach(x=>m.set(x.category,(m.get(x.category)??0)+toCents(x.amount)));return [...m.entries()].sort((a,b)=>b[1]-a[1])},[monthly]);
 const bills=useMemo(()=>cards.map(x=>[x,cardInvoiceTotal(x,transactions)] as const),[cards,transactions]); const totalBill=bills.reduce((s,[,v])=>s+v,0), totalLimit=cards.reduce((s,x)=>s+toCents(x.credit_limit),0);
 const series=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const k=d.toISOString().slice(0,7);return {key:k,...monthTotals(transactions.filter(x=>x.date.startsWith(k)))}}),[transactions]);
 function close(){setModal(null);setEditTx(null);setEditCard(null);setEditGoal(null);setAdjustGoal(null)}
 async function saveTx(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),amount=num(f.get("amount")),txType:TransactionType=f.get("type")==="income"?"income":"expense",credit=txType==="expense"&&f.get("payment")==="credit"?String(f.get("credit_card_id")??"")||null:null,p={description:String(f.get("description")??"").trim(),amount,type:txType,category:String(f.get("category")??"").trim(),date:String(f.get("date")),credit_card_id:credit,note:String(f.get("note")??"").trim()||null};if(!p.description||!p.category||amount<=0)return alert("Preencha descrição, categoria e valor válido.");if(f.get("payment")==="credit"&&!credit)return alert("Selecione o cartão usado.");setSaving(true);try{const s=createClient(),r=editTx?await s.from("transactions").update(p).eq("id",editTx.id).select().single():await s.from("transactions").insert(p).select().single();if(r.error||!r.data)throw r.error;const item=transaction(r.data);setTransactions(xs=>editTx?xs.map(x=>x.id===item.id?item:x):[item,...xs]);close();alert("Movimentação salva.")}catch{alert("Não foi possível salvar a movimentação.")}finally{setSaving(false)}}
 async function saveCard(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),limit=num(f.get("credit_limit")),last=String(f.get("last_four")??"").replace(/\D/g,""),p={name:String(f.get("name")??"").trim(),credit_limit:limit,closing_day:Number(f.get("closing_day")),due_day:Number(f.get("due_day")),brand:String(f.get("brand")??"").trim()||null,last_four:last||null,color:String(f.get("color")??"#2f72ff")};if(!p.name||limit<=0||p.closing_day<1||p.closing_day>31||p.due_day<1||p.due_day>31||(last&&last.length!==4))return alert("Informe os dados do cartão corretamente.");setSaving(true);try{const s=createClient(),r=editCard?await s.from("credit_cards").update(p).eq("id",editCard.id).select().single():await s.from("credit_cards").insert(p).select().single();if(r.error||!r.data)throw r.error;const item=card(r.data);setCards(xs=>editCard?xs.map(x=>x.id===item.id?item:x):[item,...xs]);close();alert("Cartão salvo.")}catch{alert("Não foi possível salvar o cartão. Verifique se a migração foi executada.")}finally{setSaving(false)}}
 async function saveGoal(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),target=num(f.get("target")),current=num(f.get("current")),p={name:String(f.get("name")??"").trim(),target,current,due_date:String(f.get("due_date")??"")||null,description:String(f.get("description")??"").trim()||null};if(!p.name||target<=0||current<0)return alert("Informe os dados da meta corretamente.");setSaving(true);try{const s=createClient(),r=editGoal?await s.from("goals").update(p).eq("id",editGoal.id).select().single():await s.from("goals").insert(p).select().single();if(r.error||!r.data)throw r.error;const item=goal(r.data);setGoals(xs=>editGoal?xs.map(x=>x.id===item.id?item:x):[item,...xs]);close();alert("Meta salva.")}catch{alert("Não foi possível salvar a meta.")}finally{setSaving(false)}}
 async function adjust(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!adjustGoal)return;const f=new FormData(e.currentTarget),delta=toCents(f.get("amount"))*(f.get("direction")==="remove"?-1:1),current=Math.max(0,toCents(adjustGoal.current)+delta);setSaving(true);try{const r=await createClient().from("goals").update({current:fromCents(current)}).eq("id",adjustGoal.id).select().single();if(r.error||!r.data)throw r.error;const item=goal(r.data);setGoals(xs=>xs.map(x=>x.id===item.id?item:x));close();alert("Progresso atualizado.")}catch{alert("Não foi possível atualizar a meta.")}finally{setSaving(false)}}
 function destroy(table:"transactions"|"credit_cards"|"goals",id:string,label:string){setConfirm({text:`Excluir “${label}”? Esta ação não pode ser desfeita.`,run:async()=>{try{const {error}=await createClient().from(table).delete().eq("id",id);if(error)throw error;if(table==="transactions")setTransactions(xs=>xs.filter(x=>x.id!==id));if(table==="credit_cards")setCards(xs=>xs.filter(x=>x.id!==id));if(table==="goals")setGoals(xs=>xs.filter(x=>x.id!==id));alert("Item excluído.")}catch{alert("Não foi possível excluir o item.")}finally{setConfirm(null)}}})}
 async function logout(){await createClient().auth.signOut();router.replace("/auth/login");router.refresh()}
 const Sidebar=()=> <aside className={`sidebar ${menu?"open":""}`}><div className="brand"><WalletCards size={21}/><b>Finanças Matheus</b><button className="icon close" onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(i=>{const Icon=i.icon;return <Link className={page===i.page?"active":""} href={i.href} key={i.page} onClick={()=>setMenu(false)}><Icon size={18}/>{i.label}</Link>})}</nav><div className="sidebar-bottom"><small>{name||"Sua conta"}</small><button onClick={()=>void logout()}><LogOut size={17}/>Sair</button></div></aside>;
 const title=nav.find(x=>x.page===page)?.label;
 return <div className="finance-app"><Sidebar/>{menu&&<button className="overlay" onClick={()=>setMenu(false)} aria-label="Fechar menu"/>}<main><header><button className="icon mobile-menu" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button><div><small>FINANÇAS MATHEUS</small><h1>{title}</h1></div><div className="header-actions"><span>{email}</span>{page!=="configuracoes"&&<button className="primary" onClick={()=>{setEditTx(null);setModal("transaction")}}><Plus size={17}/>Nova movimentação</button>}</div></header>{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}{loading?<Loading/>:error?<section className="error"><h2>Não foi possível abrir o sistema</h2><p>{error}</p><button className="primary" onClick={()=>void load()}>Tentar novamente</button></section>:<>{page==="dashboard"&&<Dashboard/>}{page==="movimentacoes"&&<Transactions/>}{page==="cartoes"&&<Cards/>}{page==="metas"&&<Goals/>}{page==="relatorios"&&<Reports/>}{page==="configuracoes"&&<Settings/>}</>}</main>{modal==="transaction"&&<TransactionModal/>}{modal==="card"&&<CardModal/>}{modal==="goal"&&<GoalModal/>}{modal==="adjust"&&<AdjustModal/>}{confirm&&<Confirm/>}</div>;
 function Dashboard(){const top=cards[0],max=cats[0]?.[1]??1;return <><section className="kpis"><Metric n="Saldo disponível" v={formatCurrency(fromCents(balance))}/><Metric n="Entradas do mês" v={formatCurrency(fromCents(totals.income))} green/><Metric n="Despesas do mês" v={formatCurrency(fromCents(totals.expense))} red/><Metric n="Economia" v={`${totals.income?Math.max(0,balance/totals.income*100).toFixed(1).replace(".",","):"0,0"}%`} purple/></section><section className="grid"><article className="panel"><Title t="Cartão de crédito" link="Cartões" href="/cartoes"/>{top?<><p className="muted">Fatura atual · vence dia {top.due_day}</p><strong className="amount">{formatCurrency(fromCents(cardInvoiceTotal(top,transactions)))}</strong><Bar v={top.credit_limit?cardInvoiceTotal(top,transactions)/toCents(top.credit_limit)*100:0}/><div className="split"><span>Disponível <b>{formatCurrency(fromCents(cardAvailable(top,transactions)))}</b></span><span>Limite <b>{formatCurrency(top.credit_limit)}</b></span></div></>:<Empty t="Cadastre um cartão para acompanhar a fatura." b="Novo cartão" f={()=>setModal("card")}/>}</article><article className="panel"><Title t="Despesas por categoria"/>{cats.length?cats.slice(0,6).map(([n,v])=><div className="category" key={n}><span>{n}</span><Bar v={v/max*100}/><b>{formatCurrency(fromCents(v))}</b></div>):<Empty t="Suas despesas aparecerão aqui."/>}</article></section><section className="grid"><article className="panel"><Title t="Evolução mensal" s="Dados reais dos últimos 6 meses"/><Chart/></article><article className="panel"><Title t="Últimas movimentações" link="Ver todas" href="/movimentacoes"/>{transactions.length?<TxList xs={transactions.slice(0,6)}/>:<Empty t="Registre sua primeira movimentação." b="Nova movimentação" f={()=>setModal("transaction")}/>}</article></section><section className="panel"><Title t="Metas em andamento" link="Ver metas" href="/metas"/>{goals.length?goals.slice(0,4).map(x=><GoalLine x={x} key={x.id}/>):<Empty t="Crie uma meta para começar." b="Nova meta" f={()=>setModal("goal")}/>}</section></>}
 function Transactions(){return <><section className="filters"><label>Período<select value={month} onChange={e=>setMonth(e.target.value)}>{months.map(x=><option value={x} key={x}>{monthName(x)}</option>)}</select></label><label className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar movimentações"/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">Todos</option><option value="income">Entradas</option><option value="expense">Despesas</option></select></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label></section><section className="panel"><Title t={`${visible.length} movimentações`} b="Nova movimentação" f={()=>{setEditTx(null);setModal("transaction")}}/>{visible.length?<TxList xs={visible} actions/>:<Empty t="Nenhuma movimentação encontrada."/>}</section></>}
 function Cards(){return <section className="cards">{cards.map(x=>{const bill=cardInvoiceTotal(x,transactions);return <article className="panel" key={x.id}><div className="card-visual" style={{background:`linear-gradient(135deg,${x.color??"#2f72ff"},#14223d)`}}><small>{x.brand||"Crédito"}</small><b>{x.name}</b><span>{x.last_four?`•••• ${x.last_four}`:"Final não informado"}</span></div><div className="actions"><div><small className="muted">Fatura atual</small><strong>{formatCurrency(fromCents(bill))}</strong></div><button className="icon" aria-label="Editar cartão" onClick={()=>{setEditCard(x);setModal("card")}}><Pencil size={16}/></button><button className="icon danger" aria-label="Excluir cartão" onClick={()=>transactions.some(t=>t.credit_card_id===x.id)?alert("Este cartão tem compras vinculadas. Reclassifique-as antes de excluir."):destroy("credit_cards",x.id,x.name)}><Trash2 size={16}/></button></div><Bar v={x.credit_limit?bill/toCents(x.credit_limit)*100:0}/><div className="split"><span>Disponível <b>{formatCurrency(fromCents(cardAvailable(x,transactions)))}</b></span><span>Vence dia <b>{x.due_day}</b></span></div><p className="muted">Fecha dia {x.closing_day} · limite {formatCurrency(x.credit_limit)}</p></article>})}<button className="add-card" onClick={()=>{setEditCard(null);setModal("card")}}><Plus/>Adicionar cartão</button></section>}
 function Goals(){return <section className="cards">{goals.map(x=><article className="panel" key={x.id}><div className="actions"><div><h2>{x.name}</h2><p className="muted">{x.description||"Sem descrição"}</p></div><button className="icon" aria-label="Editar meta" onClick={()=>{setEditGoal(x);setModal("goal")}}><Pencil size={16}/></button><button className="icon danger" aria-label="Excluir meta" onClick={()=>destroy("goals",x.id,x.name)}><Trash2 size={16}/></button></div><strong className="amount">{formatCurrency(x.current)} <small>de {formatCurrency(x.target)}</small></strong><Bar v={goalProgress(x)} purple/><div className="split"><span>{goalProgress(x).toFixed(1).replace(".",",")}% concluído</span><button className="secondary" onClick={()=>{setAdjustGoal(x);setModal("adjust")}}>Ajustar valor</button></div>{x.due_date&&<p className="muted">Prazo: {formatDate(x.due_date)}</p>}</article>)}<button className="add-card" onClick={()=>{setEditGoal(null);setModal("goal")}}><Plus/>Nova meta</button></section>}
 function Reports(){return <><section className="filters"><label>Período<select value={month} onChange={e=>setMonth(e.target.value)}>{months.map(x=><option value={x} key={x}>{monthName(x)}</option>)}</select></label></section><section className="kpis"><Metric n="Entradas" v={formatCurrency(fromCents(totals.income))} green/><Metric n="Despesas" v={formatCurrency(fromCents(totals.expense))} red/><Metric n="Saldo" v={formatCurrency(fromCents(balance))}/><Metric n="Fatura atual" v={formatCurrency(fromCents(totalBill))} purple/></section><section className="grid"><article className="panel"><Title t="Evolução de 6 meses"/><Chart/></article><article className="panel"><Title t="Categorias"/>{cats.length?cats.map(([n,v])=><div className="category" key={n}><span>{n}</span><Bar v={v/(cats[0]?.[1]??1)*100}/><b>{formatCurrency(fromCents(v))}</b></div>):<Empty t="Ainda não há despesas no período."/>}</article></section></>}
 function Settings(){async function save(e:FormEvent){e.preventDefault();setSaving(true);try{const {error}=await createClient().auth.updateUser({data:{full_name:name.trim()}});if(error)throw error;alert("Configurações salvas.")}catch{alert("Não foi possível salvar as configurações.")}finally{setSaving(false)}}return <section className="settings"><form className="panel form" onSubmit={save}><Title t="Conta" s="Informações do seu perfil"/><label>Nome<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><label>E-mail<input value={email} disabled/></label><button className="primary" disabled={saving}>{saving?"Salvando…":"Salvar alterações"}</button></form><article className="panel"><Title t="Sessão e privacidade"/><p className="muted">Os registros financeiros são protegidos por usuário no banco de dados.</p><button className="secondary" onClick={()=>void logout()}><LogOut size={16}/>Encerrar sessão</button></article></section>}
 function TxList({xs,actions=false}:{xs:Transaction[];actions?:boolean}){return <div className="tx-list">{xs.map(x=><div className="tx" key={x.id}><i className={x.type}>{x.type==="income"?<ArrowUpRight size={17}/>:<ArrowDownLeft size={17}/>}</i><div><b>{x.description}</b><small>{x.category} · {formatDate(x.date)}</small></div><strong className={x.type}>{x.type==="income"?"+":"−"} {formatCurrency(x.amount)}</strong>{actions&&<span className="tx-buttons"><button className="icon" aria-label="Editar movimentação" onClick={()=>{setEditTx(x);setModal("transaction")}}><Pencil size={15}/></button><button className="icon danger" aria-label="Excluir movimentação" onClick={()=>destroy("transactions",x.id,x.description)}><Trash2 size={15}/></button></span>}</div>)}</div>}
 function Title({t,s,link,href,b,f}:{t:string;s?:string;link?:string;href?:string;b?:string;f?:()=>void}){return <div className="title"><div><h2>{t}</h2>{s&&<p>{s}</p>}</div>{link&&href&&<Link href={href}>{link}</Link>}{b&&<button className="secondary" onClick={f}><Plus size={15}/>{b}</button>}</div>}
 function Metric({n,v,green,red,purple}:{n:string;v:string;green?:boolean;red?:boolean;purple?:boolean}){return <article className={`metric ${green?"green":red?"red":purple?"purple":""}`}><span>{n}</span><strong>{v}</strong></article>}
 function Bar({v,purple=false}:{v:number;purple?:boolean}){return <div className={`bar ${purple?"purple":""}`}><i style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></div>}
 function Empty({t,b,f}:{t:string;b?:string;f?:()=>void}){return <div className="empty"><p>{t}</p>{b&&<button className="secondary" onClick={f}>{b}</button>}</div>}
 function GoalLine({x}:{x:Goal}){return <div className="goal-line"><div><b>{x.name}</b><span>{formatCurrency(x.current)} de {formatCurrency(x.target)}</span></div><Bar v={goalProgress(x)} purple/><small>{goalProgress(x).toFixed(1).replace(".",",")}% concluído</small></div>}
 function Chart(){const max=Math.max(1,...series.flatMap(x=>[x.income,x.expense])),points=(k:"income"|"expense")=>series.map((x,i)=>`${i*120},${180-x[k]/max*160}`).join(" ");return <div className="chart"><svg viewBox="0 0 600 190"><title>Entradas e despesas reais por mês</title><polyline className="income-line" points={points("income")}/><polyline className="expense-line" points={points("expense")}/></svg><p><span className="income-dot"/>Entradas <span className="expense-dot"/>Despesas</p><div>{series.map(x=><small key={x.key}>{new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(new Date(`${x.key}-01T12:00:00`)).replace(".","")}</small>)}</div></div>}
 function Frame({title,children}:{title:string;children:React.ReactNode}){return <div className="modal-bg" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><button className="icon close" onClick={close} aria-label="Fechar"><X/></button><h2>{title}</h2>{children}</section></div>}
 const Buttons=({label="Salvar"}:{label?:string})=><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Salvando…":label}</button></div>;
 function TransactionModal(){const x=editTx;return <Frame title={x?"Editar movimentação":"Nova movimentação"}><form className="form" onSubmit={saveTx}><label>Descrição<input name="description" required maxLength={120} defaultValue={x?.description??""}/></label><div className="two"><label>Valor<input name="amount" type="number" step="0.01" min="0.01" required defaultValue={x?.amount??""}/></label><label>Data<input name="date" type="date" required defaultValue={x?.date??today()}/></label></div><div className="two"><label>Tipo<select name="type" defaultValue={x?.type??"expense"}><option value="expense">Despesa</option><option value="income">Entrada</option></select></label><label>Categoria<select name="category" defaultValue={x?.category??"Outros"}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="two"><label>Pagamento<select name="payment" defaultValue={x?.credit_card_id?"credit":"account"}><option value="account">Conta / débito</option><option value="credit">Cartão de crédito</option></select></label><label>Cartão<select name="credit_card_id" defaultValue={x?.credit_card_id??""}><option value="">Selecione</option>{cards.map(c=><option value={c.id} key={c.id}>{c.last_four?`${c.name} •••• ${c.last_four}`:c.name}</option>)}</select></label></div><label>Observação <small>opcional</small><textarea name="note" defaultValue={x?.note??""} maxLength={500}/></label><Buttons/></form></Frame>}
 function CardModal(){const x=editCard;return <Frame title={x?"Editar cartão":"Novo cartão"}><form className="form" onSubmit={saveCard}><label>Nome<input name="name" required defaultValue={x?.name??""}/></label><div className="two"><label>Bandeira<input name="brand" defaultValue={x?.brand??""}/></label><label>Últimos 4 dígitos<input name="last_four" inputMode="numeric" maxLength={4} defaultValue={x?.last_four??""}/></label></div><label>Limite<input name="credit_limit" type="number" required min="0.01" step="0.01" defaultValue={x?.credit_limit??""}/></label><div className="two"><label>Fechamento<input name="closing_day" type="number" required min="1" max="31" defaultValue={x?.closing_day??1}/></label><label>Vencimento<input name="due_day" type="number" required min="1" max="31" defaultValue={x?.due_day??10}/></label></div><label>Cor<input name="color" type="color" defaultValue={x?.color??"#2f72ff"}/></label><Buttons/></form></Frame>}
 function GoalModal(){const x=editGoal;return <Frame title={x?"Editar meta":"Nova meta"}><form className="form" onSubmit={saveGoal}><label>Nome<input name="name" required defaultValue={x?.name??""}/></label><div className="two"><label>Objetivo<input name="target" type="number" required min="0.01" step="0.01" defaultValue={x?.target??""}/></label><label>Valor atual<input name="current" type="number" required min="0" step="0.01" defaultValue={x?.current??0}/></label></div><label>Prazo <small>opcional</small><input name="due_date" type="date" defaultValue={x?.due_date??""}/></label><label>Descrição <small>opcional</small><textarea name="description" defaultValue={x?.description??""}/></label><Buttons/></form></Frame>}
 function AdjustModal(){return <Frame title={`Ajustar ${adjustGoal?.name??"meta"}`}><form className="form" onSubmit={adjust}><label>Operação<select name="direction"><option value="add">Adicionar valor</option><option value="remove">Remover valor</option></select></label><label>Valor<input name="amount" type="number" required min="0.01" step="0.01" autoFocus/></label><Buttons label="Atualizar"/></form></Frame>}
 function Confirm(){return <Frame title="Confirmar exclusão"><p>{confirm?.text}</p><div className="modal-actions"><button className="secondary" onClick={()=>setConfirm(null)}>Cancelar</button><button className="danger-button" onClick={()=>void confirm?.run()}>Excluir</button></div></Frame>}
}
function Loading(){return <div className="loading"><i/>Carregando seus dados financeiros…</div>}
